from decouple import config
from datetime import timedelta


DATABASE_URL = config("DATABASE_URL")
JWT_SECRET_KEY = config("ADMIN_JWT_ACCESS_SECRET")
JWT_REFRESH_SECRET_KEY = config("ADMIN_JWT_REFRESH_SECRET")
JWT_ALGORITHM = config("ADMIN_JWT_ALGORITHM")
JWT_ACCESS_TOKEN_EXPIRE_MINUTES = 60
JWT_REFRESH_TOKEN_EXPIRE_DAYS = 7
NOTIFICATION_BASE_URL = config("NOTIFICATION_URL")

