# Generated by Django 5.1.3 on 2024-11-30 16:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_low_stock_alert_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuthenticationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('token_expiry', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TwoFactorAuthenticationToken',
            },
        ),
    ]
