# Generated by Django 5.1.3 on 2024-12-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_twofactorauthenticationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.CharField(blank=True, choices=[('TRIAL', 'Free Trial'), ('GOLD', 'Gold plan'), ('VIP', 'VIP'), ('EXPIRED', 'Out of subscription')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
