# Generated by Django 5.1.3 on 2024-12-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_subscription_user_subscription_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Business Owner'), ('ATTENDANT', 'Business Attendant')], default='OWNER', max_length=10),
        ),
    ]
