# Generated by Django 5.1.3 on 2024-12-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_is_subscribed_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
