# Generated by Django 5.1.3 on 2025-01-20 12:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_user_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('address', models.TextField()),
                ('qualification', models.CharField(max_length=255)),
                ('sales_experience', models.BooleanField()),
                ('gender', models.CharField()),
                ('password', models.CharField(max_length=500)),
                ('is_default_password', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_login', models.DateTimeField(null=True)),
                ('referral_code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'marketer',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='marketter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.marketter'),
        ),
    ]
