# Generated by Django 5.1.3 on 2025-01-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_marketter_user_marketter'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketter',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
