# Generated by Django 5.1.3 on 2025-02-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_marketter_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketter',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
