# Generated by Django 5.1.3 on 2025-02-04 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_marketter_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketter',
            name='is_approved',
        ),
    ]
