# Generated by Django 5.1.3 on 2025-02-17 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_marketter_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='marketter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketer_user', to='authentication.marketter'),
        ),
    ]
