# Generated by Django 5.1.3 on 2024-11-15 12:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product')),
                ('expiry_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('low_stock_threshold', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('IN-STOCK', 'In stock'), ('LOW', 'Low stock'), ('OUT-OF-STOCK', 'Out of stock')], default='IN-STOCK', max_length=12)),
                ('currency', models.CharField(default='NGN', max_length=5)),
                ('cost_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('selling_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage off'), ('PRICE', 'Price Slash')], default='PERCENTAGE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.supplier')),
            ],
        ),
    ]
