# Generated by Django 5.1.3 on 2024-11-16 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Pcs', 'Pieces'), ('Kg', 'Kilogram'), ('Bag', 'Bags')], default='Pcs', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='low_stock_threshold',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
