# Generated by Django 5.1.3 on 2024-11-16 14:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_supplier_balance_supplier_debt_supplier_email_and_more'),
        ('product', '0002_product_unit_alter_product_low_stock_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStocking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('cost_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('selling_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('restock_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.supplier')),
            ],
        ),
    ]
