# Generated by Django 5.1.3 on 2024-11-29 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
    ]
