# Generated by Django 5.1.3 on 2025-01-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_sku_alter_productstocking_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstocking',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='PAID', max_length=10),
        ),
    ]
