# Generated by Django 5.1.3 on 2025-01-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productstocking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstocking',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productstocking',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productstocking',
            name='payment_method',
            field=models.CharField(choices=[('FULL', 'Paid in full'), ('PART', 'Partial'), ('CREDIT', 'Credit')], default='FULL', max_length=15),
        ),
    ]
