# Generated by Django 5.1.3 on 2025-01-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productstocking_amount_paid_productstocking_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Pcs', 'Pieces'), ('Kg', 'Kilogram'), ('Bag', 'Bags'), ('Box', 'Box'), ('Ctn', 'Ctn'), ('Ltd', 'Ltd'), ('Pair', 'Pair'), ('Gram', 'Gram'), ('Feet', 'Feet'), ('Roll', 'Roll'), ('Meter', 'Meter'), ('Mil', 'Mil'), ('Bottle', 'Bottle'), ('Bundle', 'Bundle'), ('Ml', 'Ml'), ('Ton', 'Ton'), ('Dozen', 'Dozen'), ('Mg', 'Mg'), ('Gr', 'Gr')], default='Pcs', max_length=10),
        ),
    ]
