# Generated by Django 5.1.3 on 2025-01-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('PRODUCT', 'Product category'), ('EXPENSES', 'Expenses category')], default='PRODUCT', max_length=10),
        ),
    ]
