# Generated by Django 5.1.3 on 2024-11-16 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('product', '0002_product_unit_alter_product_low_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='debt',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default='akinolasamson1234@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='purchase_value',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='wallet',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SupplierFunding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveBigIntegerField()),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('MYCLIQ', 'Mycliq')], default='CASH', max_length=15)),
                ('type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('REFUND', 'Refund')], default='DEPOSIT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierRestock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_supply_restock', to='product.product')),
            ],
        ),
    ]
