# Generated by Django 5.1.3 on 2024-11-16 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_supplier_balance_supplier_debt_supplier_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierrestock',
            name='supplier',
            field=models.ForeignKey(default='9915e7c3-95f5-4491-b84e-79d694a28ede', on_delete=django.db.models.deletion.CASCADE, to='business.supplier'),
            preserve_default=False,
        ),
    ]
