# Generated by Django 5.1.3 on 2024-11-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_supplierrestock_supplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplierRestock',
        ),
    ]
