# Generated by Django 5.1.3 on 2024-11-28 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_delete_supplierrestock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='attendants',
            field=models.ManyToManyField(blank=True, related_name='attendance_businesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
