# Generated by Django 5.1.3 on 2024-11-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_business_attendants'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='currency',
            field=models.CharField(default='NGN', max_length=5),
        ),
    ]
