# Generated by Django 5.1.3 on 2024-11-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_business_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'United state dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound Sterling'), ('KES', 'Kenya Shillings')], default='NGN', max_length=5),
        ),
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.CharField(choices=[('SUPERMARKET', 'Supermarkets'), ('RESTAURANT', 'Restaurant'), ('SALON', 'Salon')], default='SUPERMARKET', max_length=50),
        ),
    ]
