# Generated by Django 5.1.3 on 2024-12-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_business_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'United state dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound Sterling'), ('JPY', 'Japanese yen'), ('CHF', 'Swiss Franc'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('NZD', 'New zealand Dollar'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('RUB', 'Russian Ruble'), ('BRL', 'Brazilian Real'), ('ZAR', 'South African Rand'), ('MXN', 'Mexican Peso'), ('SGD', 'Singapore Dollar'), ('HKD', 'Hong kong Dollar'), ('SEK', 'Swwedish Krona'), ('KES', 'Kenya Shillings'), ('GHS', 'Ghana Cedis')], default='NGN', max_length=5),
        ),
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.CharField(choices=[('Food & Restaurant', 'Food & Restaurant'), ('Beauty & Personal Care', 'Beauty & Personal Care'), ('Book & Stationery', 'Book & Stationery'), ('Minimart & Retail', 'Minimart & Retail'), ('Electronics & Gadget', 'Electronics & Gadget'), ('Laundry', 'Laundry'), ('Salon Business', 'Salon Business'), ('Pharmacy & Health Products', 'Pharmacy & Health Products'), ('Home & Furniture', 'Home & Furniture'), ('Construction Material & Suppliers', 'Construction Material & Suppliers'), ('Logistics & Others', 'Logistics & Others')], default='Food & Restaurant', max_length=50),
        ),
    ]
