# Generated by Django 5.1.3 on 2024-11-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
