# Generated by Django 5.1.3 on 2024-11-30 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_business_currency'),
        ('sale', '0003_alter_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='business',
            field=models.ForeignKey(default='fba1e08e-9c04-4bf8-ba85-c1436d314780', on_delete=django.db.models.deletion.CASCADE, to='business.business'),
            preserve_default=False,
        ),
    ]
