# Generated by Django 5.1.3 on 2025-01-03 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_businessbank'),
        ('sale', '0004_sale_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_payment_history', to='business.businessbank'),
        ),
    ]
