# Generated by Django 5.1.3 on 2025-01-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_paymenthistory_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduct',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
