# Generated by Django 5.1.3 on 2025-01-17 15:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_saleproduct_profit'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_services', to='sale.sale')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_sales', to='service.service')),
            ],
        ),
    ]
