# Generated by Django 5.1.3 on 2025-02-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_saleservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleservice',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
