# Generated by Django 5.1.3 on 2024-12-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_subscriptionplans_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptions',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('SUCCESSFUL', 'Successful payment')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='usersubscriptions',
            name='payment_method',
            field=models.CharField(choices=[('PAYSTACK', 'Paystack')], default='PAYSTACK', max_length=50),
        ),
    ]
