# Generated by Django 5.1.3 on 2025-01-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usersubscriptions_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptions',
            name='payment_method',
            field=models.CharField(choices=[('PAYSTACK', 'Paystack'), ('VELVPAY', 'Velvepay')], default='PAYSTACK', max_length=50),
        ),
    ]
