# Generated by Django 5.1.3 on 2025-01-19 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usersubscriptions_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('monthly', models.IntegerField()),
                ('quarterly', models.IntegerField()),
                ('biannually', models.IntegerField()),
                ('annually', models.IntegerField()),
                ('no_of_users', models.IntegerField(default=1)),
                ('no_of_attendants', models.IntegerField(default=0)),
                ('no_of_business', models.IntegerField(default=0)),
                ('store_front', models.BooleanField(default=False)),
                ('sales_count', models.IntegerField()),
                ('invoice_count', models.IntegerField(default=0)),
                ('customers_count', models.IntegerField(default=5)),
                ('track_income', models.BooleanField(default=True)),
                ('in_store_checkout', models.BooleanField(default=False)),
                ('bulk_sms', models.BooleanField(default=False)),
                ('bulk_email', models.BooleanField(default=False)),
                ('bank_expenses_traking', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='usersubscriptions',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscriptions',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscriptions',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.syncsubscription'),
        ),
        migrations.DeleteModel(
            name='SubscriptionPlans',
        ),
    ]
