# Generated by Django 5.1.3 on 2025-01-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_syncsubscription_usersubscriptions_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptions',
            name='duration_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUATERLY', 'Quarterly'), ('BIANNUAL', 'Biannual'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=15),
        ),
    ]
