# Generated by Django 5.1.3 on 2025-01-22 13:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_marketter_is_verified'),
        ('user', '0006_usersubscriptions_duration_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketerCommision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketer_commision', to='authentication.marketter')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_by_user', to='user.usersubscriptions')),
            ],
        ),
    ]
