# Generated by Django 5.1.3 on 2025-01-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_marketercommision'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncsubscription',
            name='code',
            field=models.CharField(default='STARTER', max_length=15),
        ),
    ]
