# Generated by Django 5.1.3 on 2025-02-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_syncsubscription_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncsubscription',
            name='inventory_count',
            field=models.IntegerField(default=0),
        ),
    ]
