# Generated by Django 5.1.3 on 2024-11-17 19:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0004_delete_supplierrestock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='customer')),
                ('email', models.EmailField(max_length=254)),
                ('email_marketting', models.BooleanField(default=False)),
                ('sms_marketting', models.BooleanField(default=False)),
                ('wallet', models.BigIntegerField(default=0)),
                ('purchase_value', models.PositiveBigIntegerField(default=0)),
                ('lastSales', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_customers', to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerWalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal')], default='DEPOSIT', max_length=10)),
                ('initial', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash Payment'), ('BANK', 'Bank Transfer')], default='CASH', max_length=4)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_ransaction', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
